<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>VideoEditor-v1.9.0-Setup</AssemblyName>
    <RootNamespace>VideoEditor.Setup</RootNamespace>
    <ApplicationIcon>..\..\assets\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\publish\v1.9.0\VideoEditor-win-x64-portable.zip" LogicalName="payload.zip" />
  </ItemGroup>
</Project>
