<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>VideoEditor</AssemblyName>
    <RootNamespace>VideoEditor</RootNamespace>
    <ApplicationIcon></ApplicationIcon>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Xabe.FFmpeg" Version="5.2.6" />
    <PackageReference Include="Xabe.FFmpeg.Downloader" Version="5.2.6" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="System.Speech" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Tools\" />
  </ItemGroup>
</Project>
